---
title: "Some leaflet tiles"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Some leaflet tiles}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rstatatools)
```

## Tiandi Map

locsf is a sf class object.

```{r}
library(leaflet)
library(leafem)
library(rstatatools)
library(sf)
leaflet() %>%
  tdtmap(type = "terrain") %>%
  addFeatures(locsf, weight = 0.1, radius = 0.1)
```

To add annotion on Tiandi map, use:

```{r}
leaflet() %>%
  tdtmap(type = "terrain") %>%
  tdtmap_annotion() %>% 
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

## GaoDe Map

```{r}
leaflet() %>%
  gdmap() %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

Annotion:

```{r}
leaflet() %>%
  gdmap(type = "satellite") %>%
  gdmap_annotion() %>% 
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

## Geoq Map 

Normal:

```{r}
leaflet() %>%
  geoqmap() %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

PurplishBlue:

```{r}
leaflet() %>%
  geoqmap(type = "PurplishBlue") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

Gray:

```{r}
leaflet() %>%
  geoqmap(type = "Gray") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

Warm:

```{r}
leaflet() %>%
  geoqmap(type = "Warm") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

ENG:

```{r}
leaflet() %>%
  geoqmap(type = "ENG") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

LabelAndBoundaryLine: 

```{r}
leaflet() %>%
  geoqmap(type = "LabelAndBoundaryLine") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

Subway:

```{r}
leaflet() %>%
  geoqmap(type = "Subway") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

WorldHydroMap: 

```{r}
leaflet() %>%
  geoqmap(type = "WorldHydroMap") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

Gray_OnlySymbol:

```{r}
leaflet() %>%
  geoqmap(type = "Gray_OnlySymbol") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

Gray_Reference:

```{r}
leaflet() %>%
  geoqmap(type = "Gray_Reference") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

PurplishBlue_OnlySymbol:

```{r}
leaflet() %>%
  geoqmap(type = "PurplishBlue_OnlySymbol") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

PurplishBlue_Reference:

```{r}
leaflet() %>%
  geoqmap(type = "PurplishBlue_Reference") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

Warm_OnlySymbol:

```{r}
leaflet() %>%
  geoqmap(type = "Warm_OnlySymbol") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```

Warm_Reference:

```{r}
leaflet() %>%
  geoqmap(type = "Warm_Reference") %>%
  addFeatures(locsf, weight = 0.1, 
              radius = 0.1, color = "red")
```
